services:
- type: web
  name: kihenge
  env: ruby

  runtime: docker
  repo: https://github.com/glerarch/kihenge
  plan: free
  envVars:
  - key: RAILS_MASTER_KEY
    sync: false
  - key: WEB_CONCURRENCY
    sync: false
  - key: RAILS_ENV
    value: production
  region: frankfurt
  dockerContext: .
  dockerfilePath: ./Dockerfile
version: "1"
